### PR TITLE
Fix CMAKE_CURRENT_SOURCE_DIR

### PR DESCRIPTION
**Pull request by Iunusov**
CMAKE_SOURCE_DIR can return wrong root, when library is used as dependency.

### CODE REVIEW

**Comment by evpobr** [comment]
@Iunusov, i hope that was fixed in 15fa0f4 of #239.

**Comment by Iunusov** [comment]
Yes, but I still getting error with your commit (cmake/TestInline.cmake is
not changed at all, but it also uses CMAKE_SOURCE_DIR instead of
CMAKE_CURRENT_SOURCE_DIR). Let's check your CmakeLists.txt and
cmake/TestInline.cmake.

**Comment by evpobr** [comment]
Ok, `TestInline.cmake` fixed, try now. It was forced push, reset last 3 commits and pull again. I know it is bad, but `wip/cmake` is almost ready, i don't want to add new commits.

Another question: do you use `add_subdirectory` to add LibSndFile project?

**Comment by Iunusov** [comment]
yes, I am using add_subdirectory() and Visual Studio 2015.

I will check.

**Comment by Iunusov** [comment]
checked, still getting errors because of wrong root:

-- Checking for inline...
*CMake Error: File D:/WIndows/Desktop/test/cmake/TestInline.c.in
<http://TestInline.c.in> does not exist*.
CMake Error at deps/libsndfile/cmake/TestInline.cmake:5 (configure_file):
  configure_file Problem configuring file

Real libsndfile location: D:\WIndows\Desktop\test\*deps*\libsndfile

**Comment by evpobr** [comment]
I'll check it.

**Comment by Iunusov** [comment]
Thanks.

**Comment by evpobr** [comment]
Yes, there are many issues when adding LibSndFile with `add_directory`. Most of them are fixed in `bugfix/cmake-out-of-source`. But tests are not working, disable them with `BUILD_TESTS=OFF`. Now i need @madebr help to fix AutoGen implementation and tests. It will take time.

Another way is to build and install `libsndfile` and use `find_package(LibSndFile)`. It works with `master` branch.

**Comment by evpobr** [comment]
I made PR #245, hope it fixes all problems.

**Comment by Iunusov** [comment]
I will check, thanks!

**Comment by Iunusov** [comment]
Checked, now it works fine without the issues.

**Comment by evpobr** [comment]
Ok. Changes are merged to master barch.

**Pull request closed without merging**
