### PR TITLE
CMake polishing

### PR DESCRIPTION
**Pull request by evpobr**
# Features

* Autogenerating sources without AutoGen! Great thanks to @madebr
* True out-of-tree builds (thanks @madebr). All generated builds are placed to separate build directory
* Add `pcm_test` and `win32_ordinal_test` to test suite
* Add examples and regtest targets
* Testing improvements - CMake internal test support files are not generated if you disable testing
* Configurable [CPack](https://cmake.org/Wiki/CMake:Packaging_With_CPack) support - you can disable it now with `ENABLE_CPACK` option set to `OFF`
* Add `ENABLE_BOW_DOCS` option. Set to `ON` to get black on white documentation style
* `ENABLE_STATIC_RUNTIME` option - set to `ON` to enable static runtime with MinGW and [Visual Studio](https://msdn.microsoft.com/en-US/library/2kzt1wy3.aspx).
* Add [config package support](https://cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#package-layout). Now you don't need to write your own FindLibSndFilecmake find module. Usage is as simple as:
```cmake
find_package (LibSndFile 1)
if (LIBSNDFILE_FOUND)
    taget_link_library (<your_target> PRIVATE sndfile-static)
endif ()
```
This work under Windows with default install location `%PROGRAMFILES%`. If you want to install LibSndFile to different location, use `LibSndFIle_DIR` option to set proper path.

# Not to be implemented

* `generate` target. Many quirks are required.
* Octave module. Really complicated detection procedure.
* [Package registry](https://cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#package-registry). Package config mode is moslty the same. Install to arbitrary location and use `LibSndFIle_DIR`.

# Screenshots

cmake

vs2017

@erikd - tell what to rebase\squash please.

### CODE REVIEW

**Comment by erikd** [comment]
Will look at this tomorrow (holiday Easter Monday).

**Comment by erikd** [comment]
This is probably best squashed into two commits, the first containing just the commits from @madebr and the second your commits. Probably worth keeping the best of the details in the commit message.

**Comment by evpobr** [comment]
@erikd , ok, how to name them?

**Comment by evpobr** [comment]
I think it is worth highlighting three important points:

**madebr:**

1.  CMake: Allow parallel out-of-tree build (71)
    * cmake: allow parallel out-of-tree build
    * cmake: remove generated files in source tree prior to generation + fix install
2.  CMake: Use CMakeAutoGen as CMake AutoGen implementation (closes 154)
    * Use CMakeAutoGen as CMake AutoGen implementation
    * Fix non-matching FOR and ENDFOR of template src/test_endswap.tpl
    * cmake: add pcm_test to test suite

**evpobr:**

3. CMake: Add package config support (71)

Everything else goes to squashed commit:

4. CMake: various fixes (closes 71)

**Comment by erikd** [comment]
I have the first one be:
```
CMake fixes

* Allow parallel out-of-tree build.
* Use CMakeAutoGen as CMake AutoGen implementation.
* Etc.
```

And the second one.
```
More CMake polishing

* Add missing test suite programs.
* Add examples/ targets.
* Improve compatibility with MSVC.
* Multiple tweaks.
```

**Comment by erikd** [comment]
Sure. Mine was just a suggestion.

**Comment by erikd** [comment]
I really prefer the issue numbers to go in the commit message body as full URLs.

**Comment by evpobr** [comment]
> I really prefer the issue numbers to go in the commit message body as full URLs.

Sure. It's just a plan here.

> Sure. Mine was just a suggestion.

In the end, I think there will be enough 3 commits - 2 from @madebr , and 1 mine.

And the last question - I want to make changes to READMEs (about CMake) & and add new CMake's module to Makefile.am. You said to make only changes to CMake in this brunch. I should do it after merging this branch?

**Comment by erikd** [comment]
> I should do it after merging this branch?

I don't mind. Either works for me.

**Comment by erikd** [comment]
Since you are committing to this branch again, I presume its not complete. If thats the case, can you take it out of "needs review" state?

**Comment by evpobr** [comment]
> Since you are committing to this branch again, I presume its not complete.

Yes, that "pre1" postfix bug isn't fixed. Found it today, trying to generate MSI install package with CPack with WiX.

**Comment by evpobr** [comment]
@erikd:

Bug fixed, documentation updated. My english is not so good, so i'm waiting your notes.

**Comment by evpobr** [comment]
@erikd, preparations done.

**Comment by madebr** [comment]
I don't think I documented this anywhere but if you'd run into some problems with the CMakeAutoGen implementation, please open a ticket at https://github.com/madebr/CMakeAutoGen/issues

**Comment by evpobr** [comment]
@madebr , thanks, i know know about your repo. Your code works just fine, that was my bug.

**Comment by bagong** [comment]
May I just say that I am really excited about what has been happening here in the last months. In conjunction with microsofts vcpkg (for ogg/flac/vorbis) it's now really easy to build a trustworthy version of libsndfile!!! Thanks a lot for this to all of you, it is really appreciated!

**Comment by evpobr** [comment]
@erikd, when are you going to review this pull request? It's time to finish with CMake development.

**Comment by evpobr** [comment]
Fix for #242 applied.

**Comment by erikd** [comment]
Sorry, been rather busy. Merged now.

**Pull request merged**
