### PR TITLE
Fix MSAN errors

### PR DESCRIPTION
**Pull request by erikd**
Fix multiple errors uncovered by Clang's Memory Sanitizer.

Closes: https://github.com/erikd/libsndfile/issues/248

@evpobr Please test this patch.

### CODE REVIEW

**Comment by evpobr** [comment]
@erikd https://github.com/erikd/libsndfile/commits/wip/appveyor-checksum-test.

**Comment by erikd** [comment]
Does this mean it passed? There's a green tick next to my commit, but later builds are red.

**Comment by evpobr** [comment]
Sorry, i was buzy. Yes, checksum test is fixed now under both x86 and x64. `misc_test_rf64` still fails.

And now win32_ordinal_test fails after 6830c42 or f614de1. My fault.

**Comment by erikd** [comment]
Can you pasted the text output for the "misc_test rf64" failure?

**Comment by evpobr** [comment]
Issue #244

**Pull request merged**
