### PR TITLE
Use modern WinAPI functions

### PR DESCRIPTION
**Pull request by evpobr**
Replace obsolete WinAPI functions `SetFilePointer` with `SetFilePointerEx`, `GetFileSize` with `GetFileSizeEx`.

New functions support 64-bit offsets directly, available at least on Win95, so nothing breaks.

Old functions are relics from Win 3.x 16-bit world.

### CODE REVIEW

**Comment by evpobr** [comment]
Should i clean my branch?

**Comment by erikd** [comment]
You need "git rebase develop" followed by "git push --force". Force push to a feature branch or your own PR branch is always ok.

**Comment by evpobr** [comment]
@erikd  done.

**Comment by erikd** [comment]
No idea why Github still thinks this is out-of-date with master. Going to try to merge it anyway and see what happens.

**Comment by erikd** [comment]
Well that seemed to work.

**Pull request merged**
