### PR TITLE
CMake Rewrite

### PR DESCRIPTION
**Pull request by syb0rg**
Made the expiramental CMake build process more robust and portable.

### CODE REVIEW

**Comment by erikd** [comment]
Until this code is actually ready to merge, I'd prefer not to have a PR. I'm watching your repo and have a clone of it on my machine so I can test and even send you PRs.

**Comment by syb0rg** [comment]
All Travis tests have passed, what more would you like CMake to do before a merge?  I need a concrete list to implement.

**Comment by erikd** [comment]
To merge it has to at least match what currently works on my machine. For my CMake build system, that means:

* It builds on Linux (tested on both x86_64 and PowerPC).
* It builds the tests on Linux and all the tests pass (x86_64 and PowerPC).

**Comment by erikd** [comment]
I also think that passing all configuration variables on the command line is a mistake and I would much prefer then written to a file like my CMake build system does.

**Comment by syb0rg** [comment]
What file are you writing to?  I'm not seeing a specific file that all those definitions are written to.

**Comment by erikd** [comment]
https://github.com/erikd/libsndfile/blob/master/CMakeLists.txt#L132

**Comment by syb0rg** [comment]
This most recent commit fails 2 out of the 38 tests (`command_test` and `dither_test`), do you have any insight on how to fix them?

**Comment by syb0rg** [comment]
Do we want the libsndfile programs compiled with the library, or a separate `make` command for it?

**Comment by erikd** [comment]
I think the make command should build everthing including the programs and examples.

**Comment by chadwackerman** [comment]
> If people want to use Open Source / Free Software components in the software they are building for Windows it is not unreasonable to expect them to install something like MSYS.

I've been building libsndfile for years on multiple platforms and it's always been a pain in the ass. I'm not sure what's so special about this library that requires all this complexity.

I really appreciate the cmake modernization work done by syb0rg. And I'd urge you to heed some of his feedback.

Also please consider hosting your docs and tarballs here as properly tagged releases. And consider posting a Dockerfile that sets up your crazy build environment if you insist on this level of complexity. This library is in many ways stuck in 2005.

**Comment by erikd** [comment]
> I've been building libsndfile for years on multiple platforms and it's always been a pain in the ass. 

And yet, you have never contributed and never even raised an issue here on Github. 

One of the few times you have raised your head on one these Github issues you were profoundly incorrect. For a reminder, see https://github.com/erikd/libsndfile/issues/127#issuecomment-210506948 .

As for the CMake build system @syb0rg is working on I will help where I can and reserve my judgment until its complete (currently it is not complete). You are also free to help him.

 > And consider posting a Dockerfile that sets up your crazy build environment

And yet, you have never raised a github issue and never specifically documented exactly *what* problems you are having. Personally I think using Docker for this is total overkill. I *know* that I can set up a Debian or Ubuntu system to build libsndfile from source with:
```
apt install autoconf autogen automake build-essentials libtool libflac-dev libogg-dev
     libvorbis-dev pkg-config
```
For other Linux distros (and even on Mac OS X with brew) the package names are the same or very similar. 

On reflection that should probably be in the Readme. If you had raised an issue here asking how to set up a system to build libsndfile from source on Linux (Docker is Linux only I believe) I would have done what I could to help and the Readme would probably have been updated.

**Comment by erikd** [comment]
@chadwackerman I have updated the README.md with explicit instructions on setting up a build environment on Linux and Mac OS X to build libsndfile from source.

**Comment by chadwackerman** [comment]
This is hilarious because you continue to miss the point. Yes, if you're on debian, getting all the stuff needed to set up your house of cards build environment is very easy! The issue is that you're incapable of seeing that many people are not on debian. But I'm glad to see your shortsightedness extends past Windows and GitHub and C++ and CMake and now includes Docker, too.

"Download tarballs containing generated files from a random non-SSL website" is a pretty remarkable engineering position in 2016.

For clarity here's an "totally overkill" Dockerfile:

    FROM ubuntu:xenial
    RUN apt-get update && apt-get -y install \
        autoconf autogen automake build-essential git libtool libflac-dev libogg-dev libvorbis-dev pkg-config
    RUN git clone --depth 1 https://github.com/erikd/libsndfile.git

Works on Linux, works on Windows, works on Mac. So. Overkill.

Even after correcting your "build-essentials" typo to "build-essential" if you actually run that you'll see it fails looking for Python. So basically even you can't type up a README that lists your required dependencies and actually builds the project. 

As a sidenote your "you don't contribute" argument is bunk for a variety of reasons. This isn't my main open source account (go figure!) and the reason I haven't shared more with your project is because it's not contributor friendly. Reading your pull request comments alone would discourage most sane people. The ancillary pieces (build system, deployments, hosting) are comically outdated. It's far easier to maintain a patch in private than deal with someone who really needs to consider hanging up his open source shoes or at a minimum seek help running the social and contributor aspects of this project.

**Comment by syb0rg** [comment]
@chadwackerman No need to be harsh, you can still get your point across in a friendly tone!

**Comment by chadwackerman** [comment]
Perhaps, but he's been screwing with a CMake build for over two years and it doesn't work yet. You stepped up to help, you're playing it straight out of the open source playbook, and he's going full pedantic-neurotic-C-coder-circa-1998 instead of taking ten minutes to actually think about your changes or how a project should be run in 2016. But hey, we got some broken build instructions out of him, that's progress.

**Comment by erikd** [comment]
On Linux I get this worning:
```
/tmp/libsndfile-syb0rg/src/common.c: In function ‘psf_rand_int32’:
/tmp/libsndfile-syb0rg/src/common.c:1349:3: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
   gettimeofday (&tv, NULL) ;
```
and this build failure:
```
[100%] Linking C executable ../sndfile-play
CMakeFiles/sndfile-play.dir/sndfile-play.c.o: In function `alsa_write_float.constprop.1':
sndfile-play.c:(.text+0x48): undefined reference to `snd_pcm_writei'
sndfile-play.c:(.text+0x151): undefined reference to `snd_pcm_prepare'
CMakeFiles/sndfile-play.dir/sndfile-play.c.o: In function `main':
sndfile-play.c:(.text.startup+0x349): undefined reference to `snd_pcm_open'
sndfile-play.c:(.text.startup+0x35d): undefined reference to `snd_pcm_nonblock'
```
Neither of which happened with my CMake build system. Would you like me to fix these?

**Comment by syb0rg** [comment]
@erikd I can reproduce the warning, but not the build error on OSX and Windows.  If you're up to it, I'd love the help!

**Comment by erikd** [comment]
I may not get to it until the weekend. Pretty buys this week.

**Comment by syb0rg** [comment]
How many checks do you pass when you run them with this build system?

**Comment by erikd** [comment]
I get:
```
The following tests FAILED:
	  7 - command_test (Failed)
	 10 - dither_test (Failed)
	 14 - fix_this (Failed)
	 28 - pipe_test (Failed)
	 33 - stdio_test (Failed)
```
Still a lot of work required to get the tests running correctly. In the autotool based build system (and my original CMake one) the tests are run via a script `tests/test_wrapper.sh` which is generated at configure time. I should probably convert that script into a C program so it is buildable and runnable anywhere.

**Comment by syb0rg** [comment]
Odd, I only have 3 tests fail on my Mac. I haven't run the tests on Windows
yet, I wonder if the results would be different on there as well.

> Still a lot of work required to get the tests running correctly.

Do you mean future work?

**Comment by erikd** [comment]
> Do you mean future work?

I mean work that has not yet been done, so yes, future work.

**Comment by syb0rg** [comment]
Only two tests fail now on macOS Sierra: `fix_this` and `dither_test`.

**Comment by erikd** [comment]
@syb0rg Yes, those two tests fail with the autotool based build as well. The code should be build, but not run.

Couple of things:

* Detection of external libs (ogg, vorbis and FLAC) doesn't seem to work for me although the autotool build system detects them (possibly related to the next point).

* The `HAVE_EXTERNAL_XIPH_LIBS` define should be in `config.h` instead of being passed on the command line.

* I still need a way to be able to specify extra warning flags (like -Werror) or build options (eg GCC/Clang sanitiers, stack smash protector etc) when building. I've tried `CFLAGS=-Werror make`, but that doesn't work. I don't care if this happens in CMake or in the generated Makefiles.

**Comment by erikd** [comment]
> The code should be build, but not run.

Actually scratch that. I need to completely revamp the test runner.

**Comment by syb0rg** [comment]
@evpobr That was just a test to see if setting those to "true" worked the same as setting them to 1.  I thought they might, and I'm considering changing them all to that since it makes the code slightly more readable.

**Comment by evpobr** [comment]
> Right, but I'm using CMAKE_SOURCE_DIR, as you saw. This creates an absolute path, and fixed compilation problems for me. I haven't had problems with doing it this way yet (on any of my test systems).

Somebody will, trying importing our CMakeLists.txt in his project. He will get config,h in his CMakeLists.txt directory. It's about CMake imported targets feature. I think i will add support for this later.

**Comment by evpobr** [comment]
@syb0rg , @erikd Test code is broken. Al least sf_version test, it is always ok. 

test_wrapper.sh compares sf_version output is to PROJECT_VERSION, but CMake's just run test, it's OK and CTest happy.

**Comment by syb0rg** [comment]
> I still need a way to be able to specify extra warning flags (like -Werror) or build options (eg GCC/Clang sanitiers, stack smash protector etc) when building. I've tried CFLAGS=-Werror make, but that doesn't work.

@erikd Right now a possible way of doing this would be with [CMake options](https://cmake.org/cmake/help/v3.0/command/option.html).  But how many flags/build options are you looking to specify?

**Comment by evpobr** [comment]
@erikd, @syb0org Agreed, options is OK, it's the same as automake options. `CFLAGS`'s analog in CMake is `CMAKE_C_FLAGS`:

` cmake . -DCMAKE_C_FLAGS=”-Werror”`

You even have `CMAKE_C_FLAGS_RELEASE` and `CMAKE_C_FLAGS_DEBUG`.

Also, in current CMake project we set -O2 flag for optimization and it is wrong. Just do

`cmake -DCMAKE_BUILD_ TYPE=Release`

and CMake will set appropriate release compiler flags (this flag is Debug by defaut).

**Comment by erikd** [comment]
Some of them are simply on/off things. For example, the current autotools build system allows `--enable-experimental` which sets `ENABLE_EXPERIMENTAL_CODE` to either `0` or `1`.

I also have an `--enable-werror` option which when on adds `-Werror` to `CFLAGS`.

However, I'd also like to be able to add things to `CFLAGS` and `CXXFLAGS` and these may not be known a-priori.  For example a new version of GCC or Clang comes out, I often read the release notes and test out new warning options. It would be really nice to be able to do this on the command line without hacking the CMake files.

**Comment by evpobr** [comment]
@ Erik's You can:

` cmake . -DCMAKE_C_FLAGS="-Werror"`

**Comment by erikd** [comment]
@evpobr Yes, saw you posted that about a minute before I posted mine. I'll try it out when I have a little time.

**Comment by syb0rg** [comment]
I've lost the time to finish working on this due to college, @evpobr looks to have continued what I started.

**Comment by erikd** [comment]
Thanks for your effort @syb0rg !

**Pull request closed without merging**
