### PR TITLE
Rework CMake build system

### PR DESCRIPTION
**Pull request by evpobr**
Squashed version of #199.

### CODE REVIEW

**Comment by erikd** [comment]
Please leave this PR exactly as it is. I will fix any issues.

**Comment by evpobr** [comment]
`.travis.yml` fix applied. results:

| compiler | time before | time after |
| -------- | ----------- | ---------- |
| gcc      | 6:27        | 3:42       |
| clang    | 5:10        | 5:40 (???) |

Also reworked `SNDFILE_EXPORTS` defining. See output form make script, generated by CMake:

    -Dlibsndfile_EXPORTS -DSNDFILE_EXPORTS

`SNDFILE_EXPORTS` is defined by me, `libsndfile_EXPORTS` by CMake for the same purpose.

Now my define removed, `libsndfile_EXPORTS` renamed to `SNDFILE_EXPORTS` with `DEFINE_SYMBOL` target property.

**Comment by evpobr** [comment]
Final bunch of fixes. Preparing Appveyor CI test with Visual Studio i found some bugs. All of them were fixed in cmake-config, but lost in this PR:

* `unistd.h` issues
* missing `ssize_t`
* `Makefile.am`, new files are added to distribution

Also `create_symbols_file` generation fails under Visual Studio, hell knows why, so `libsndfile.def.in.cmake` is restored back. I think using `create_symbols_file` to generate just one file is not a good idea anyway.

**Comment by evpobr** [comment]
I hope #207 was fixed with changes i made today, will test later. Also cross-compilation seems to be fixed.

**Comment by evpobr** [comment]
@erikd, large file support now configured properly with CMake, tested under 32-bit Lunux machine. No, not exactly. Tested under Windows 10 64-bit under Windows Subsystem for Linux (based on Ubuntu 16.04 64-bit) with arm-linux-gnueabi-gcc compiler toolchain (32-bit)  😲 

Output:

```
-- The C compiler identification is GNU 4.7.3
-- The CXX compiler identification is GNU 4.7.3
-- Check for working C compiler: /usr/bin/arm-linux-gnueabi-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabi-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--
--
-- Checking large files support...
--
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
--
-- Checking size of off_t without any definitions:
-- Check size of off_t
-- Check size of off_t - done
-- Checking of off_t without any definitions: 4
--
-- Checking size of off_t with _FILE_OFFSET_BITS=64:
-- Check size of off_t
-- Check size of off_t - done
-- Checking size of off_t with _FILE_OFFSET_BITS=64: 8
--
-- Result of checking large files support: supported
```

So both large files & cross-compiling works. @erikd , please, spend your precious time on the review of this PR.

**Comment by erikd** [comment]
@evpobr I do superficial reviews on github, but I do the main par of my reviewing (especially for large PRs) by applying the PR to a local branch. That means that whenever you change the PR while I am in the middle of reviewing it, I effectively have to start again.

I was also informed of a rather serious bug in libsndfile on Thursday of this week. Unfortunately that take precedence over this.

**Comment by evpobr** [comment]
> That means that whenever you change the PR while I am in the middle of reviewing it, I effectively have to start again.

Sorry. Ten days from you there was no news, so I allowed myself to add a couple of fixes (`offset_t` configuring). Today there were no functional changes, just a rebase on your master branch.

> I was also informed of a rather serious bug in libsndfile on Thursday of this week. Unfortunately that take precedence over this.

Add issue please, my be i can help. It would also be useful to create the next [milestone](https://guides.github.com/features/issues/) #172 (v1.0.28?) and add blocking issues to it, so that everyone can see exactly what needs to be done.

**Comment by erikd** [comment]
> Add issue please

Not appropriate for a security issue.

**Comment by erikd** [comment]
Had a quick look.

Currently, when building with `Scripts/cmake-build.sh` all the libraries and binaries end up in the root build directory. If the advised way of building using CMake is to build it outside the source tree, then this script should be updated to do that. Changing `make check` to `make test` at the same time would be a good idea. Would also be a good idea to look at the way CMake is called in that script especially to add whatever is needed to make sure `-Werror` is passed to the C and C++ compilers.

I'm also not super happy with the way the test output looks. When the autotool build system run the tests, it does so in a specific order and does not add its own extra output (like `5/135 Test   #5:`). Not too sure how easy it is to improve this. Probably not worth it if its a lot of work.

**Comment by evpobr** [comment]
> Currently, when building with `Scripts/cmake-build.sh` all the libraries and binaries end up in the root build directory. If the advised way of building using CMake is to build it outside the source tree, then this script should be updated to do that. Changing `make check` to `make test` at the same time would be a good idea.

The problem with the script in parameter passing, the user may want to add a lot of parameters (the simplest example is `CMAKE_BUILD_TYPE`), and the script does not allow this. About out-of-source builds - it's also a matter of passing parameters to the script. Also, no one interferes with making different builds with different parameters in different directories and it's again problematic to do with the script. Therefore, I think that the script should be deleted and the build procedure with CMake described in README.

> Would also be a good idea to look at the way CMake is called in that script especially to add whatever is needed to make sure `-Werror` is passed to the C and C++ compilers.

This has already been [done](https://github.com/evpobr/libsndfile/blob/cmake-config-revised/cmake/SndFileChecks.cmake#L182).

> I'm also not super happy with the way the test output looks.

I do not see any options how to do it.

**Comment by erikd** [comment]
> The problem with the script in parameter passing, the user may want to add a lot of parameters (the simplest example is CMAKE_BUILD_TYPE), and the script does not allow this.

The script is about a simple basic default (mostly for me, so i can remember how to do it, because I'm pretty sure I will be using the autotool build system for the foreseeable future). Scripts can also take command line parameters and interogate environment variables.

**Comment by evpobr** [comment]
> Had a quick look.

To simplify your work - maybe  quick look is enough right now? CMake code is  independent of the rest of the libsndfile code. It makes sense to look at the changes in the Makefile.am, the changes in existing C code etc. All the rest can be commited right now without any particular consequences. At last, it passes tests and it can make builds under Windows, unlike existing CMake code.

Then you can spend any time to rewiew new code, and I will make small changes with particular commits.

**Comment by evpobr** [comment]
> The script is about a simple basic default (mostly for me, so i can remember how to do it, because I'm pretty sure I will be using the autotool build system for the foreseeable future). Scripts can also take command line parameters and interogate environment variables.

I think correct code is:

```
mkdir cmake-build
cd cmake-build
cmake ..
cmake --build .
ctest -V

```

But i still don't understand how to pass parameters.

What if i want:

`cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS:BOOL=ON`

Or, if i want:

`cd cmake-build-arm`

Or no verbose test output:

`ctest`

**Comment by erikd** [comment]
> To simplify your work - maybe quick look is enough right now?

Another problem is that the bug that I was notified of during the week (I have a fix for it, but haven't pushed it yest) is serious enough to require a new release, I'm concerned that including a brand new CMake build systems that will result in a a string of github issues and bug report emails that I don't have the time to deal with.

**Comment by evpobr** [comment]
> Another problem is that the bug that I was notified of during the week (I have a fix for it, but haven't pushed it yest) is serious enough to require a new release.

No problem. 

> I'm concerned that including a brand new CMake build systems that will result in a a string of github issues and bug report emails that I don't have the time to deal with.

No problem, i'm ready to continue CMake build development in next release.

**Comment by evpobr** [comment]
If you think that my help can be useful, you can add me to the list of collaborators. GitHub gives ability to set up rights. You can [protect](https://help.github.com/articles/about-protected-branches/) the master branch and I can make commits there only with your [approval](https://help.github.com/articles/approving-a-pull-request-with-required-reviews/). If you need my help to review the requester, you can ask for my approval. Just checked it out with my [liblod](evpobr/liblod) an that was amazing. I can help with all CMake-related requests and with trivial C-code PRs.

This is only an offer that can be useful to you. I will continue to work on the project in any case.

**Comment by evpobr** [comment]
Thanks :-)

Master branch is not protected. It's better to disallow force pushes my pull requests without your approval, without all tests passed, and pull requests with merge conflicts:

protected-branch

Also it's better to disable ability to do `Merge pull request...`:

no-merge


What is the name of of new bugfix release? 1.0.28? I want to add milestone.

**Comment by erikd** [comment]
Thanks. And next release will be 1.0.28.

**Comment by evpobr** [comment]
@erikd, so, it's time to merge it?

**Comment by erikd** [comment]
I spent about 10 hours over this weekend tracking down and fixing these bugs and preparing the new release, so I need a break.

**Comment by evpobr** [comment]
Investigating [tests building with MSVC](https://github.com/evpobr/libsndfile/tree/cmake-msvc). Some code changes were required. MSVC build passes tests now.

**Comment by erikd** [comment]
I've added the "sfconfig.h" includes to the two files that needed. Its on master now.

**Comment by evpobr** [comment]
Rebased on master to resolve merge conflict.

**Comment by erikd** [comment]
Merged. Thanks.

**Pull request closed without merging**
