### PR TITLE
add BWF v2 loudness parameters

### LINKED ISSUE #479: SF_BROADCAST_INFO doesn't support BWF Version 2
Currently SF_BROADCAST_INFO is limted to version 1. Version 2 added 5 R.128 loudness metadata (first 10 Bytes of currently reserved space). Basically, these are just 5 int16_t values (little-endian). 

have a look here:
https://tech.ebu.ch/docs/tech/tech3285.pdf

Version 2 is a substantial revision of Version 1 which incorporates loudness metadata (in accordance with EBU R 128 [2]) and which takes account of the publication of Supplements 1 – 6 and other relevant documentation. This version is fully compatible with Versions 0 and 1, but users who wish to ensure that their files meet the requirements of EBU Recommendation R 128 will need to ensure that their systems can read and write the loudness metadata.

### PR DESCRIPTION
**Pull request by Moonbase59**
BWF v2 PR for review, fixes #479.
All 141 tests passing here (Linux Mint 19.2), plus the results agree with [BWF MetaEdit](https://mediaarea.net/BWFMetaEdit/Download/Debian).

Please comment.

### CODE REVIEW

**Comment by Moonbase59** [comment]
Hope I did all this rebasing/squashing stuff correctly, never before done that …

**Comment by erikd** [comment]
There should not be any merge commit if you have rebase corrected.

Assuming you have my repo set as a remote (which I will call `upstream` here), from your PR branch:
```
git fetch upstream
git rebase upstream/master
```

**Comment by Moonbase59** [comment]
Thanks for the help, I actually hadn’t (yet) defined your repo as upstream (must have assumed the forking does that). Changed that and rebased my PR branch as suggested. Hope this works out.

**Comment by erikd** [comment]
The upstream has to be defined locally in your machine whereas "fork on github" is a github operation.

Still doesn't seem to be a single commit and the merge commit should disappear with the rebase.

**Comment by Moonbase59** [comment]
Odd. Any idea what the git command is to "fold the commits into one"? I seem not really to find it (given that git has so many options).

**Comment by Moonbase59** [comment]
Hmm. I tried it again (assuming adding the upstream has messed something up) and now get:

```
matthias@v-studio2:~/Projekte/libsndfile$ git rebase upstream/master 
Zunächst wird der Branch zurückgespult, um Ihre Änderungen
darauf neu anzuwenden ...
Wende an: add BWF v2 loudness parameters
Wende an: Remove typecast on REPLACE_IF_NEW_INT
Wende an: adapt coding style as required
Wende an: add BWF v2 loudness parameters
Verwende Informationen aus der Staging-Area, um ein Basisverzeichnis nachzustellen ...
M	programs/common.c
M	programs/common.h
M	programs/sndfile-info.c
M	programs/sndfile-metadata-get.c
M	programs/sndfile-metadata-set.c
M	src/broadcast.c
M	src/sndfile.h.in
M	src/wavlike.c
M	tests/command_test.c
Falle zurück zum Patchen der Basis und zum 3-Wege-Merge ...
Keine Änderungen -- Patches bereits angewendet.
Wende an: add BWF v2 loudness parameters
Verwende Informationen aus der Staging-Area, um ein Basisverzeichnis nachzustellen ...
M	programs/common.c
M	programs/common.h
M	programs/sndfile-info.c
M	programs/sndfile-metadata-get.c
M	programs/sndfile-metadata-set.c
M	src/broadcast.c
M	src/sndfile.h.in
M	src/wavlike.c
M	tests/command_test.c
Falle zurück zum Patchen der Basis und zum 3-Wege-Merge ...
automatischer Merge von programs/common.c
KONFLIKT (Inhalt): Merge-Konflikt in programs/common.c
error: Merge der Änderungen fehlgeschlagen.
Anwendung des Patches fehlgeschlagen bei 0005 add BWF v2 loudness parameters
Benutzen Sie 'git am --show-current-patch', um den
fehlgeschlagenen Patch zu sehen.

Lösen Sie alle Konflikte manuell auf, markieren Sie diese mit
"git add/rm <konfliktbehaftete_Dateien>" und führen Sie dann
"git rebase --continue" aus.
Sie können auch stattdessen diesen Commit auslassen, indem
Sie "git rebase --skip" ausführen.
Um abzubrechen und zurück zum Zustand vor "git rebase" zu gelangen,
führen Sie "git rebase --abort" aus.
```

**Comment by erikd** [comment]
What is the output of the following:
```
git fetch upstream
git rev-parse upstream.master
```

**Comment by Moonbase59** [comment]
```
matthias@v-studio2:~/Projekte/libsndfile$ git fetch upstream
matthias@v-studio2:~/Projekte/libsndfile$ git rev-parse upstream.master
upstream.master
fatal: mehrdeutiges Argument 'upstream.master': unbekannter Commit oder Pfad existiert nicht
im Arbeitsverzeichnis
Benutzen Sie '--', um Pfade und Commits zu trennen, ähnlich wie:
'git <Befehl> [<Commit>...] -- [<Datei>...]'
matthias@v-studio2:~/Projekte/libsndfile$ LC_ALL=C git rev-parse upstream.master
upstream.master
fatal: ambiguous argument 'upstream.master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
matthias@v-studio2:~/Projekte/libsndfile$ 
```

**Comment by erikd** [comment]
Ok, so now:
```
git rebase upstream/master
```

**Comment by erikd** [comment]
This may be useful: https://sethrobertson.github.io/GitFixUm/fixup.html

**Comment by Moonbase59** [comment]
Thanks for the help, I think I found out now. Lerning new things every day …

With all these tries (and the merges), I had messed up my branch quite a bit.
So I went and did an interactive rebase (in my branch):
```
git rebase --interactive 22c2fa64c29a32f3a20434a873429110b74a06bc
```
picking the original commit, squashing the next two and dropping the rest.

Then I force-pushed to my `origin bwf-v2` (instead of doing a `git pull` what I’ve done before because git suggested it)
```
git push -f
```
and _this_ seems to have done it like you wished for (a "clean" 1-commit PR).

Please verify and thanks again for getting me along!

**Comment by erikd** [comment]
Git is a complex, but very powerful tool. It is well worth the time learning some of the more advanced features.

Anyway, I have merged this manually anyway as there were a fewer really minor formatting fixed I wanted to apply.

Thanks for your work on this!

**Comment by Moonbase59** [comment]
Thank _you_ for _libsndfile_ and for the merge! Being 60 years of age now, I’m happy that I can still learn new things everyday, and still contribute a little. :-)

**Comment by erikd** [comment]
You are only a couple of 4 years older than me!

**Pull request closed without merging**
