### PR TITLE
Fix zero-as-null-pointer-constant-warning

### PR DESCRIPTION
**Pull request by MartinDelille**
This PR simply replace 0 or NULL by nullptr. It allow compiling the code with the following compiler flags:

```
-Werror -Wzero-as-null-pointer-constant
```

### CODE REVIEW

**Comment by erikd** [comment]
```
In file included from examples/sndfilehandle.cc:22:0:
./src/sndfile.hh:75:4: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
    SndfileHandle (void) : p (nullptr) {} ;
    ^
./src/sndfile.hh: In constructor ‘SndfileHandle::SndfileHandle()’:
./src/sndfile.hh:75:30: error: ‘nullptr’ was not declared in this scope
    SndfileHandle (void) : p (nullptr) {} ;
```
What do I need to do to fix this?

**Comment by MartinDelille** [comment]
I just fixed the problem.

**Comment by erikd** [comment]
Please squash these commits into a single commit and this is ready to go.

**Comment by MartinDelille** [comment]
Squashed!

**Comment by erikd** [comment]
Thanks!

**Comment by MartinDelille** [comment]
Do you plan a new release including this fix?

**Comment by erikd** [comment]
Yes, but not sure how long it will take.

**Pull request merged**
