### PR TITLE
sndfile-salvage.c: add missing headers, fixes #162

### LINKED ISSUE #162: MSVC build: sndfile-salvage fails because of missing unistd.h
Here is compiler output:

    sndfile-salvage.c(40): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

### PR DESCRIPTION
**Pull request by evpobr**

### CODE REVIEW

**Comment by erikd** [comment]
Manually merged this to the `cmake-config` branch.

**Comment by evpobr** [comment]
@erikd, may be it is better to create `develop` branch from `master` and put all new not related to CMake code there?

**Comment by erikd** [comment]
I don't see how that will make anything easier. Having two active branches (`master` and `cmake-config`) is already painful. Adding a third active branch could only make it more complicated.

People usually only use a `develop` branch when they expect it to break occasionally. I rarely if ever break `master`.

**Comment by evpobr** [comment]
Well, it is better do nothing now. But our `cmake-config` is actually `develop`, the name is confusing.

If you work alone, the one master branch is OK. But `master/develop` is not bad approach.

All stable code is in `master`, do not commit there directly. From `master` branch you create `develop` for active development. When `develop` is ready to release, merge it back to `master`. You don't commit directly to `develop`, you make feature branches, when it is ready merge it back to develop, but before do `git rebase develop` to avoid that pointless "Merged branch ..." commits. And everything is good - clean history, you will not break `master` or `develop` branch, participants do not interfere with each other.

**Comment by erikd** [comment]
Unfortunately I don't think what you suggest fits our problem.

We have a `master` branch which is under continuing development and development branch `cmake-config`. In order for you to continue work on the `cmake-config` branch, some commits from the `master` branch need to be cherry picked onto the `cmake-config` branch in order for you to make progress.

If I was working by myself on both branches, I would simply rebase `cmake-config` against master as needed, but I can't do that because if I force push the rebased `cmake-config` branch it makes your life difficult.

I don't know of anything that will work better in our situation.

**Comment by evpobr** [comment]
> If I was working by myself on both branches, I would simply rebase cmake-config against master as needed, but I can't do that because if I force push the rebased cmake-config branch it makes your life difficult.

But i always rebase my PR branches before i send you pull request, so it wil not make my life difficult :=)

Merge PRs to master, rebase cmake-config on master and it will not harm my branches.

Just do not modify or delete commits in remote branches `master` and `cmake-config`, and we are OK.

**Comment by erikd** [comment]
Unfortunately, `cmake-config` cannot be rebased from `master` because a numbers of conflicts deep in the commit history of the `cmake-config` branch.  I worked through it this time but its a real pain in the neck.

**Comment by evpobr** [comment]
Maybe it is time to sqaush them in one commit and merge to some master-based branch (develop e.g.).

**Comment by erikd** [comment]
For the next two weeks I will be traveling for business and will have much less time to work on libsndfile.

During this time, maybe you should just push commits to a single PR and I will merge them to `cmake-config` branch when I have time.

**Pull request closed without merging**
