### PR TITLE
Add AppVeyor CI script

### PR DESCRIPTION
**Pull request by evpobr**
Adds AppVeyor CI integration to test with Visual Studio.

Also adds required fix for `win32_ordinal_test` since it fails under Windows. 

Generated DEF file name is `libsndfile-1.def` with both Autotools and CMake:

https://github.com/erikd/libsndfile/blob/fa92cc4b8832f9651f178f81cd8d69c063c686b7/configure.ac#L597

https://github.com/erikd/libsndfile/blob/fa92cc4b8832f9651f178f81cd8d69c063c686b7/CMakeLists.txt#L399-L401

But `win32_ordinal_test` tries to check DLL against `libsndfile.def`:

https://github.com/erikd/libsndfile/blob/fa92cc4b8832f9651f178f81cd8d69c063c686b7/tests/win32_ordinal_test.c#L94

And it is the only failing test on `master` branch:

```
1>------ Build started: Project: RUN_TESTS, Configuration: Debug Win32 ------
1>Test project C:/Users/user/Source/Repos/libsndfile/CMakeBuild
1>        Start   1: test_main
1>  1/137 Test   #1: test_main ........................   Passed    1.83 sec
1>        Start   2: sfversion
1>  2/137 Test   #2: sfversion ........................   Passed    1.35 sec
1>        Start   3: error_test
1>  3/137 Test   #3: error_test .......................   Passed    1.27 sec
1>        Start   4: ulaw_test
1>  4/137 Test   #4: ulaw_test ........................   Passed    1.42 sec
1>        Start   5: alaw_test
1>  5/137 Test   #5: alaw_test ........................   Passed    0.68 sec
1>        Start   6: dwvw_test
1>  6/137 Test   #6: dwvw_test ........................   Passed    0.60 sec
1>        Start   7: command_test
1>  7/137 Test   #7: command_test .....................   Passed    0.91 sec
1>        Start   8: floating_point_test
1>  8/137 Test   #8: floating_point_test ..............   Passed   20.87 sec
1>        Start   9: checksum_test
1>  9/137 Test   #9: checksum_test ....................   Passed    0.79 sec
1>        Start  10: scale_clip_test
1> 10/137 Test  #10: scale_clip_test ..................   Passed    0.86 sec
1>        Start  11: headerless_test
1> 11/137 Test  #11: headerless_test ..................   Passed    0.57 sec
1>        Start  12: rdwr_test
1> 12/137 Test  #12: rdwr_test ........................   Passed    0.51 sec
1>        Start  13: locale_test
1> 13/137 Test  #13: locale_test ......................   Passed    0.62 sec
1>        Start  14: win32_ordinal_test
1> 14/137 Test  #14: win32_ordinal_test ...............***Failed    0.75 sec
1>        Start  15: cpp_test
1> 15/137 Test  #15: cpp_test .........................   Passed    0.76 sec
1>        Start  16: external_libs_test
1> 16/137 Test  #16: external_libs_test ...............   Passed    0.74 sec
1>        Start  17: format_check_test
1> 17/137 Test  #17: format_check_test ................   Passed    2.96 sec
1>        Start  18: channel_test
1> 18/137 Test  #18: channel_test .....................   Passed    1.52 sec
1>        Start  19: pcm_test
1> 19/137 Test  #19: pcm_test .........................   Passed    1.91 sec
1>        Start  20: g72x_test
1> 20/137 Test  #20: g72x_test ........................   Passed    1.51 sec
1>        Start  21: write_read_test_aiff
1> 21/137 Test  #21: write_read_test_aiff .............   Passed    5.37 sec
1>        Start  22: lossy_comp_test_aiff_ulaw
1> 22/137 Test  #22: lossy_comp_test_aiff_ulaw ........   Passed    1.32 sec
1>        Start  23: lossy_comp_test_aiff_alaw
1> 23/137 Test  #23: lossy_comp_test_aiff_alaw ........   Passed    0.26 sec
1>        Start  24: lossy_comp_test_aiff_gsm610
1> 24/137 Test  #24: lossy_comp_test_aiff_gsm610 ......   Passed    0.32 sec
1>        Start  25: peak_chunk_test_aiff
1> 25/137 Test  #25: peak_chunk_test_aiff .............   Passed    1.58 sec
1>        Start  26: header_test_aiff
1> 26/137 Test  #26: header_test_aiff .................   Passed    1.54 sec
1>        Start  27: misc_test_aiff
1> 27/137 Test  #27: misc_test_aiff ...................   Passed    1.45 sec
1>        Start  28: string_test_aiff
1> 28/137 Test  #28: string_test_aiff .................   Passed    1.61 sec
1>        Start  29: multi_file_test_aiff
1> 29/137 Test  #29: multi_file_test_aiff .............   Passed    1.31 sec
1>        Start  30: aiff_rw_test
1> 30/137 Test  #30: aiff_rw_test .....................   Passed    0.93 sec
1>        Start  31: write_read_test_au
1> 31/137 Test  #31: write_read_test_au ...............   Passed    2.85 sec
1>        Start  32: lossy_comp_test_au_ulaw
1> 32/137 Test  #32: lossy_comp_test_au_ulaw ..........   Passed    0.19 sec
1>        Start  33: lossy_comp_test_au_alaw
1> 33/137 Test  #33: lossy_comp_test_au_alaw ..........   Passed    0.16 sec
1>        Start  34: lossy_comp_test_au_g721
1> 34/137 Test  #34: lossy_comp_test_au_g721 ..........   Passed    0.26 sec
1>        Start  35: lossy_comp_test_au_g723
1> 35/137 Test  #35: lossy_comp_test_au_g723 ..........   Passed    0.47 sec
1>        Start  36: header_test_au
1> 36/137 Test  #36: header_test_au ...................   Passed    0.12 sec
1>        Start  37: misc_test_au
1> 37/137 Test  #37: misc_test_au .....................   Passed    0.10 sec
1>        Start  38: multi_file_test_au
1> 38/137 Test  #38: multi_file_test_au ...............   Passed    0.10 sec
1>        Start  39: write_read_test_caf
1> 39/137 Test  #39: write_read_test_caf ..............   Passed    2.94 sec
1>        Start  40: lossy_comp_test_caf_ulaw
1> 40/137 Test  #40: lossy_comp_test_caf_ulaw .........   Passed    0.21 sec
1>        Start  41: lossy_comp_test_caf_alaw
1> 41/137 Test  #41: lossy_comp_test_caf_alaw .........   Passed    0.25 sec
1>        Start  42: header_test_caf
1> 42/137 Test  #42: header_test_caf ..................   Passed    0.17 sec
1>        Start  43: peak_chunk_test_caf
1> 43/137 Test  #43: peak_chunk_test_caf ..............   Passed    0.14 sec
1>        Start  44: misc_test_caf
1> 44/137 Test  #44: misc_test_caf ....................   Passed    0.13 sec
1>        Start  45: chunk_test_caf
1> 45/137 Test  #45: chunk_test_caf ...................   Passed    1.51 sec
1>        Start  46: string_test_caf
1> 46/137 Test  #46: string_test_caf ..................   Passed    0.13 sec
1>        Start  47: long_read_write_test_alac
1> 47/137 Test  #47: long_read_write_test_alac ........   Passed    1.57 sec
1>        Start  48: write_read_test_wav
1> 48/137 Test  #48: write_read_test_wav ..............   Passed    3.90 sec
1>        Start  49: lossy_comp_test_wav_pcm
1> 49/137 Test  #49: lossy_comp_test_wav_pcm ..........   Passed    0.20 sec
1>        Start  50: lossy_comp_test_wav_ima
1> 50/137 Test  #50: lossy_comp_test_wav_ima ..........   Passed    0.37 sec
1>        Start  51: lossy_comp_test_wav_msadpcm
1> 51/137 Test  #51: lossy_comp_test_wav_msadpcm ......   Passed    0.36 sec
1>        Start  52: lossy_comp_test_wav_ulaw
1> 52/137 Test  #52: lossy_comp_test_wav_ulaw .........   Passed    0.22 sec
1>        Start  53: lossy_comp_test_wav_alaw
1> 53/137 Test  #53: lossy_comp_test_wav_alaw .........   Passed    0.20 sec
1>        Start  54: lossy_comp_test_wav_gsm610
1> 54/137 Test  #54: lossy_comp_test_wav_gsm610 .......   Passed    0.30 sec
1>        Start  55: lossy_comp_test_wav_g721
1> 55/137 Test  #55: lossy_comp_test_wav_g721 .........   Passed    0.28 sec
1>        Start  56: peak_chunk_test_wav
1> 56/137 Test  #56: peak_chunk_test_wav ..............   Passed    0.11 sec
1>        Start  57: header_test_wav
1> 57/137 Test  #57: header_test_wav ..................   Passed    0.16 sec
1>        Start  58: misc_test_wav
1> 58/137 Test  #58: misc_test_wav ....................   Passed    0.10 sec
1>        Start  59: string_test_wav
1> 59/137 Test  #59: string_test_wav ..................   Passed    0.18 sec
1>        Start  60: multi_file_test_wav
1> 60/137 Test  #60: multi_file_test_wav ..............   Passed    0.09 sec
1>        Start  61: chunk_test_wav
1> 61/137 Test  #61: chunk_test_wav ...................   Passed    0.15 sec
1>        Start  62: write_read_test_w64
1> 62/137 Test  #62: write_read_test_w64 ..............   Passed    1.70 sec
1>        Start  63: lossy_comp_test_w64_ima
1> 63/137 Test  #63: lossy_comp_test_w64_ima ..........   Passed    0.30 sec
1>        Start  64: lossy_comp_test_w64_msadpcm
1> 64/137 Test  #64: lossy_comp_test_w64_msadpcm ......   Passed    0.27 sec
1>        Start  65: lossy_comp_test_w64_ulaw
1> 65/137 Test  #65: lossy_comp_test_w64_ulaw .........   Passed    0.19 sec
1>        Start  66: lossy_comp_test_w64_alaw
1> 66/137 Test  #66: lossy_comp_test_w64_alaw .........   Passed    0.18 sec
1>        Start  67: lossy_comp_test_w64_gsm610
1> 67/137 Test  #67: lossy_comp_test_w64_gsm610 .......   Passed    0.23 sec
1>        Start  68: header_test_w64
1> 68/137 Test  #68: header_test_w64 ..................   Passed    0.12 sec
1>        Start  69: misc_test_w64
1> 69/137 Test  #69: misc_test_w64 ....................   Passed    0.09 sec
1>        Start  70: write_read_test_rf64
1> 70/137 Test  #70: write_read_test_rf64 .............   Passed    1.38 sec
1>        Start  71: header_test_rf64
1> 71/137 Test  #71: header_test_rf64 .................   Passed    0.17 sec
1>        Start  72: misc_test_rf64
1> 72/137 Test  #72: misc_test_rf64 ...................   Passed    0.13 sec
1>        Start  73: string_test_rf64
1> 73/137 Test  #73: string_test_rf64 .................   Passed    0.10 sec
1>        Start  74: peak_chunk_test_rf64
1> 74/137 Test  #74: peak_chunk_test_rf64 .............   Passed    0.10 sec
1>        Start  75: chunk_test_rf64
1> 75/137 Test  #75: chunk_test_rf64 ..................   Passed    0.11 sec
1>        Start  76: write_read_test_raw
1> 76/137 Test  #76: write_read_test_raw ..............   Passed    2.49 sec
1>        Start  77: lossy_comp_test_raw_ulaw
1> 77/137 Test  #77: lossy_comp_test_raw_ulaw .........   Passed    0.23 sec
1>        Start  78: lossy_comp_test_raw_alaw
1> 78/137 Test  #78: lossy_comp_test_raw_alaw .........   Passed    0.21 sec
1>        Start  79: lossy_comp_test_raw_gsm610
1> 79/137 Test  #79: lossy_comp_test_raw_gsm610 .......   Passed    0.23 sec
1>        Start  80: lossy_comp_test_vox_adpcm
1> 80/137 Test  #80: lossy_comp_test_vox_adpcm ........   Passed    0.27 sec
1>        Start  81: raw_test
1> 81/137 Test  #81: raw_test .........................   Passed    3.17 sec
1>        Start  82: write_read_test_paf
1> 82/137 Test  #82: write_read_test_paf ..............   Passed    0.87 sec
1>        Start  83: header_test_paf
1> 83/137 Test  #83: header_test_paf ..................   Passed    0.14 sec
1>        Start  84: misc_test_paf
1> 84/137 Test  #84: misc_test_paf ....................   Passed    0.13 sec
1>        Start  85: write_read_test_svx
1> 85/137 Test  #85: write_read_test_svx ..............   Passed    0.41 sec
1>        Start  86: header_test_svx
1> 86/137 Test  #86: header_test_svx ..................   Passed    0.12 sec
1>        Start  87: misc_test_svx
1> 87/137 Test  #87: misc_test_svx ....................   Passed    0.10 sec
1>        Start  88: write_read_test_nist
1> 88/137 Test  #88: write_read_test_nist .............   Passed    1.26 sec
1>        Start  89: lossy_comp_test_nist_ulaw
1> 89/137 Test  #89: lossy_comp_test_nist_ulaw ........   Passed    0.24 sec
1>        Start  90: lossy_comp_test_nist_alaw
1> 90/137 Test  #90: lossy_comp_test_nist_alaw ........   Passed    0.20 sec
1>        Start  91: header_test_nist
1> 91/137 Test  #91: header_test_nist .................   Passed    0.16 sec
1>        Start  92: misc_test_nist
1> 92/137 Test  #92: misc_test_nist ...................   Passed    0.14 sec
1>        Start  93: write_read_test_ircam
1> 93/137 Test  #93: write_read_test_ircam ............   Passed    1.51 sec
1>        Start  94: lossy_comp_test_ircam_ulaw
1> 94/137 Test  #94: lossy_comp_test_ircam_ulaw .......   Passed    0.23 sec
1>        Start  95: lossy_comp_test_ircam_alaw
1> 95/137 Test  #95: lossy_comp_test_ircam_alaw .......   Passed    0.21 sec
1>        Start  96: header_test_ircam
1> 96/137 Test  #96: header_test_ircam ................   Passed    0.15 sec
1>        Start  97: misc_test_ircam
1> 97/137 Test  #97: misc_test_ircam ..................   Passed    0.15 sec
1>        Start  98: write_read_test_voc
1> 98/137 Test  #98: write_read_test_voc ..............   Passed    0.36 sec
1>        Start  99: lossy_comp_test_voc_ulaw
1> 99/137 Test  #99: lossy_comp_test_voc_ulaw .........   Passed    0.19 sec
1>        Start 100: lossy_comp_test_voc_alaw
1>100/137 Test #100: lossy_comp_test_voc_alaw .........   Passed    0.21 sec
1>        Start 101: header_test_voc
1>101/137 Test #101: header_test_voc ..................   Passed    0.11 sec
1>        Start 102: misc_test_voc
1>102/137 Test #102: misc_test_voc ....................   Passed    0.11 sec
1>        Start 103: write_read_test_mat4
1>103/137 Test #103: write_read_test_mat4 .............   Passed    1.68 sec
1>        Start 104: header_test_mat4
1>104/137 Test #104: header_test_mat4 .................   Passed    0.15 sec
1>        Start 105: misc_test_mat4
1>105/137 Test #105: misc_test_mat4 ...................   Passed    0.09 sec
1>        Start 106: write_read_test_mat5
1>106/137 Test #106: write_read_test_mat5 .............   Passed    2.35 sec
1>        Start 107: header_test_mat5
1>107/137 Test #107: header_test_mat5 .................   Passed    0.17 sec
1>        Start 108: misc_test_mat5
1>108/137 Test #108: misc_test_mat5 ...................   Passed    0.13 sec
1>        Start 109: write_read_test_pvf
1>109/137 Test #109: write_read_test_pvf ..............   Passed    0.70 sec
1>        Start 110: header_test_pvf
1>110/137 Test #110: header_test_pvf ..................   Passed    0.13 sec
1>        Start 111: misc_test_pvf
1>111/137 Test #111: misc_test_pvf ....................   Passed    0.11 sec
1>        Start 112: lossy_comp_test_xi_dpcm
1>112/137 Test #112: lossy_comp_test_xi_dpcm ..........   Passed    0.20 sec
1>        Start 113: write_read_test_htk
1>113/137 Test #113: write_read_test_htk ..............   Passed    0.21 sec
1>        Start 114: header_test_htk
1>114/137 Test #114: header_test_htk ..................   Passed    0.10 sec
1>        Start 115: misc_test_htk
1>115/137 Test #115: misc_test_htk ....................   Passed    0.10 sec
1>        Start 116: write_read_test_avr
1>116/137 Test #116: write_read_test_avr ..............   Passed    0.71 sec
1>        Start 117: header_test_avr
1>117/137 Test #117: header_test_avr ..................   Passed    0.10 sec
1>        Start 118: misc_test_avr
1>118/137 Test #118: misc_test_avr ....................   Passed    0.09 sec
1>        Start 119: write_read_test_sds
1>119/137 Test #119: write_read_test_sds ..............   Passed    0.56 sec
1>        Start 120: header_test_sds
1>120/137 Test #120: header_test_sds ..................   Passed    0.09 sec
1>        Start 121: misc_test_sds
1>121/137 Test #121: misc_test_sds ....................   Passed    0.09 sec
1>        Start 122: write_read_test_sd2
1>122/137 Test #122: write_read_test_sd2 ..............   Passed    0.82 sec
1>        Start 123: lossy_comp_test_wve
1>123/137 Test #123: lossy_comp_test_wve ..............   Passed    0.29 sec
1>        Start 124: write_read_test_mpc2k
1>124/137 Test #124: write_read_test_mpc2k ............   Passed    0.29 sec
1>        Start 125: header_test_mpc2k
1>125/137 Test #125: header_test_mpc2k ................   Passed    0.11 sec
1>        Start 126: misc_test_mpc2k
1>126/137 Test #126: misc_test_mpc2k ..................   Passed    0.09 sec
1>        Start 127: write_read_test_flac
1>127/137 Test #127: write_read_test_flac .............   Passed    0.48 sec
1>        Start 128: compression_size_test_flac
1>128/137 Test #128: compression_size_test_flac .......   Passed    2.39 sec
1>        Start 129: string_test_flac
1>129/137 Test #129: string_test_flac .................   Passed    0.78 sec
1>        Start 130: ogg_test
1>130/137 Test #130: ogg_test .........................   Passed    2.46 sec
1>        Start 131: compression_size_test_vorbis
1>131/137 Test #131: compression_size_test_vorbis .....   Passed    0.78 sec
1>        Start 132: lossy_comp_test_ogg_vorbis
1>132/137 Test #132: lossy_comp_test_ogg_vorbis .......   Passed    0.24 sec
1>        Start 133: string_test_ogg
1>133/137 Test #133: string_test_ogg ..................   Passed    0.13 sec
1>        Start 134: misc_test_ogg
1>134/137 Test #134: misc_test_ogg ....................   Passed    0.11 sec
1>        Start 135: stdio_test
1>135/137 Test #135: stdio_test .......................   Passed    2.21 sec
1>        Start 136: pipe_test
1>136/137 Test #136: pipe_test ........................   Passed    2.25 sec
1>        Start 137: virtual_io_test
1>137/137 Test #137: virtual_io_test ..................   Passed    2.23 sec
1>
1>99% tests passed, 1 tests failed out of 137
```

### CODE REVIEW

**Comment by erikd** [comment]
For the `win32_ordinal_test.c` problem, isn't it possible to test first one version of the name and then the other and use whichever works?

**Comment by evpobr** [comment]
We don't use `libsndfile.def` anywhere, why check it?

**Comment by erikd** [comment]
[win32_ordinal_test.c](https://github.com/erikd/libsndfile/blob/fa92cc4b8832f9651f178f81cd8d69c063c686b7/tests/win32_ordinal_test.c#L94) reads the `.def` file. That test should try reading `libsndfile-1.def` and if that fails, try read `libsndfile.def`.

**Comment by evpobr** [comment]
I'm tired to explain the same thing. Just check Autotools and CMake toolchains. They never use `libsndfile.def`, they use `libsndfile-1.def`. Hell knows when we changed that name, but we forgot to fix `win32_ordinal_test.c` to check with `libsndfile-1.def`.

Just run clean build and test under MinGW, you will see fail in that test.

**Comment by erikd** [comment]
Ok, will fix `win32_ordinal_test.c`. 

is the file `src/libsndfile.def.in` still needed?

**Comment by evpobr** [comment]
Ha, it is still configured in `configure.ac`:

https://github.com/erikd/libsndfile/blob/af9d26411b2d82dbdc23e4b8021507bcc1a38a7e/configure.ac#L664-L666

but never used:

https://github.com/erikd/libsndfile/blob/af9d26411b2d82dbdc23e4b8021507bcc1a38a7e/configure.ac#L596-L597

https://github.com/erikd/libsndfile/blob/af9d26411b2d82dbdc23e4b8021507bcc1a38a7e/CMakeLists.txt#L399-L401

https://github.com/erikd/libsndfile/blob/af9d26411b2d82dbdc23e4b8021507bcc1a38a7e/CMakeLists.txt#L420-L422

**Comment by erikd** [comment]
Merged. Thanks!

**Pull request merged**
