### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by evpobr**
[EditorConfig](http://editorconfig.org/) helps developers define and maintain consistent coding styles between different editors and IDEs.

### CODE REVIEW

**Comment by erikd** [comment]
Squash that into a single commit and I'll take it.

**Comment by evpobr** [comment]
@erikd, do you use tab size of 8 chars? And what is `libsndfile` coding style, K&R?

**Comment by erikd** [comment]
libsndfile is not K&R style. Tabs stops are 4 spaces.

**Comment by evpobr** [comment]
Small fixes: simplified code, removed K&R style (not supported as well).

**Comment by erikd** [comment]
You will need to rebase this PR against the master branch for me to be able to merge it.

**Pull request closed without merging**
