### PR TITLE
Fix CMake's ENABLE_TESTING option behaviour

### PR DESCRIPTION
**Pull request by evpobr**
Prevent generation of test support files if tests are disabled.

### CODE REVIEW

**Comment by erikd** [comment]
Two commits for three changed lines? Why?

**Comment by evpobr** [comment]
> Two commits for three changed lines? Why?

Pros:

* Because they are small polishing commits, not result of large work like 1c0ea87
* They fix one thing per commit: easy to test, easy to use `git-bisect`
* Commit messages are self-descriptive
* I'm testing now under Linux and Windows, fixing what i found. Anyone who clones your repo will get fixes right now, not waiting weeks and months, .... years. It is not joke, see issue #71

> On top of 5 CMake related commits in the last week.

Add yours :smile: Seriously, i want to end up with CMake as quickly as possible. After that i will try to help you with other issues.

> Can't this be developed on a branch and merged when its done?

Of course. But what happens next? We merge bunch of commits at one time? We squash them to one ugly commit like 1c0ea87?

**Comment by erikd** [comment]
> They fix one thing per commit: easy to test, easy to use git-bisect

If you have 100 tiny CMake commits in the tree it makes git bisect more difficult and time consuming when I'm trying to find code bugs.

Yes, get the CMake build system fixed on a branch and then merge it on one commit with an commit message that details all the things that commit fixes/changes. This one big CMake commit should only touch CMake related files. If there are changes required elsewhere, they should go into master separately.

This is what I did for a series of commits leading up to 681831a404ac. This series of commits started with 50920d61d on a separate branch. Commit 681831a404ac stated out as one or more commits to each individual file. When I as had everything working I pulled each of the commits leading up to 681831a404ac into master one at a time, making sure they built and passed the tests.

**Comment by evpobr** [comment]
OK, this commit could be squashed to one. But i'm pretty sure it should be singalone commit, fixing one bug.

> If you have 100 tiny CMake commits in the tree it makes git bisect more difficult and time consuming when I'm trying to find code bugs.

I don't plan to make 100 small commits. My roadmap is:

* Big commit fixing tests after #226 - add missing tests, fix building under Win32
* Add examples
* `ENABLE_BOW_DOCS` option
* `ENABLE_STATIC_RUNTIME` option useful for Win32
* Add targets exporting
* Add package config module
* Add regtest
* Add Octave modules

Do you really want one squashed commit of that?

> This is what I did for a series of commits leading up to 681831a. This series of commits started with 50920d6 on a separate branch. Commit 681831a stated out as one or more commits to each individual file. When I as had everything working I pulled each of the commits leading up to 681831a into master one at a time, making sure they built and passed the tests.

Agreed. There are features that should be developed from start to the end in a separate branch and then squashed into one commit, Opus support for example. Or add a bunch of new tests to CMake, it's better to squash these similar commits to one. But in case of bug fixing i think it's better to make small polishing commits. Look at @SoapGentoo commits, it is good example of what i want.

**Comment by erikd** [comment]
> Do you really want one squashed commit of that?

Yes, there is nothing there that is ever going to be useful during a git bisect.

> Look at @SoapGentoo commits, it is good example of what i want.

In hinsight, i tthink so of those commits should have be squashed. Specifically, a87b68ce3c04b, e1ac9d94c34c0d, 88956f7ac2dca3 and 0fd257e43228c, all making minor changes the autotool build system.

I consider the code to be the most important thing in the repo. The next most important thing is the primary build system which at the moment is autotools. Of tertiary importance is the secondary build system. I think the number of commits should be in rough proportion to their importance.

**Comment by evpobr** [comment]
@erikd, i obey your rules. But maybe this will help you change your mind. Just quick search "Git best practices":

> [Git branching and tagging best practices](http://softwareengineering.stackexchange.com/questions/165725/git-branching-and-tagging-best-practices)

> In short: Best practice is branch out, merge often and keep always in sync.
> There are pretty clear conventions about keeping your code in a separate branches from master branch:

> - You are about to make an implementation of major or disruptive change
> - You are about to make some changes that might not be used
> - You want to experiment on something that you are not sure it will work

> When you are told to branch out, others might have something they need to do in master
> Rule of thumb is after branching out, you should keep in sync with the master branch. Because eventually you need to merge it back to master. In order to avoid a huge complicated mess of conflicts when merging back, you should commit often, merge often.

[A Few Modest Best Practices for Git](https://chriskottom.com/blog/2014/02/a-few-modest-best-practices-for-git/)

> Keep your commits tight.
This is the logical extension of the previous tip. The commit log of a well-managed repository tells a story, and so when you’re reviewing changes using git status and git diff, you should be looking for small commits that implement a single logical change to the code base and can be described with a simple statement. If the commit message you have in mind contains multiple sentences, semicolons, conjunctions, or lots of commas, it’s a good indication that you might need to try to break it up into two or more smaller commits.

[Version Control Best Practices](https://www.git-tower.com/learn/git/ebook/en/command-line/appendix/best-practices)

> Commit Related Changes

> A commit should be a wrapper for related changes. For example, fixing two different bugs should produce two separate commits. Small commits make it easier for other team members to understand the changes and roll them back if something went wrong. With tools like the staging area and the ability to stage only parts of a file, Git makes it easy to create very granular commits.

> Commit Often

> Committing often keeps your commits small and, again, helps you commit only related changes. Moreover, it allows you to share your code more frequently with others. That way it’s easier for everyone to integrate changes regularly and avoid having merge conflicts. Having few large commits and sharing them rarely, in contrast, makes it hard both to solve conflicts and to comprehend what happened.

> Don’t Commit Half-Done Work

> You should only commit code when it’s completed. This doesn’t mean you have to complete a whole, large feature before committing. Quite the contrary: split the feature’s implementation into logical chunks and remember to commit early and often. But don’t commit just to have something in the repository before leaving the office at the end of the day. If you’re tempted to commit just because you need a clean working copy (to check out a branch, pull in changes, etc.) consider using Git’s “Stash” feature instead.

[Commit Often, Perfect Later, Publish Once: Git Best Practices](https://sethrobertson.github.io/GitBestPractices/)

> People resist this out of some sense that this is ugly, limits git-bisection functionality, is confusing to observers, and might lead to accusations of stupidity. Well, I'm here to tell you that resisting this is ignorant. Commit Early And Often. If, after you are done, you want to pretend to the outside world that your work sprung complete from your mind into the repository in utter perfection with each concept fully thought out and divided into individual concept-commits, well git supports that: see Sausage Making below. However, don't let tomorrow's beauty stop you from performing continuous commits today.

[Git Best Practices: Workflow Guidelines](https://www.lullabot.com/articles/git-best-practices-workflow-guidelines)

> Small, logical commits
> CVS and Subversion encouraged large, single commits due to limitations in their branching model. This is especially apparent with the Drupal project, where a single-commit patch-based workflow is still in use. There are a few problems with large monolithic commits:

> * git blame becomes much less useful, as the commit message on given lines of code will usually be something like "Ticket #123: Add progress bars to video series." instead of "Ticket #123: Add updated jQuery UI library for progress bars."
> * History of the development of code is lost. With large commits, the process of code development is obscured and not discoverable within git.
> * git bisect becomes near useless. Even when debugging manually by checking out different commits, having granular commits makes it much simpler to find the lines of code that are actually the source of the bug.

**Comment by erikd** [comment]
Really? I have been really patient with you. I have spend *hours* of my very valuable time on you and I feel I have very very little to show for it. The vast majority of what you have posted of "git best practices" supports what I have been asking of you. I could take apart most of the points you posted above and use them to support my arguments. I'm not going to because I have better things to do.

From here on, I am going to be very much more careful about how I spend my time.

**Comment by evpobr** [comment]
@erikd, please spend a few more minutes of your valuable time on me.

I didn't mean to offend you or anything, I spent 8 months developing CMake toolchain for libsndfile. It was hard work.  I have a job if you want to now. My time is no less valuable than yours.

I hope you will not argue that the development is very slow. If you're buzy you need collaborators. I wanted to help you because I think libsndfile is great and it deserves better. I like collaboration idea in the spirit of Open Source and GitHub. But it looks like you are not very happy about it and are not going to change something.

You don't want to merge small, useful, self-descriptive commit just because it is small. It turns out very important the number of lines in the commit, as well as the number of commits in the repository. What do we develop - sndfile library or a history of commits? And notice - the commit itself follows both your recommendations and recommended Git practices.

Making `cmake` branch will slow down development without real benefits. Squashing commits with different fixes from that branch will make not make commits history better but will increase the risk of merging conflicts when working together.

I'm feeling sad that you do not want to make life a bit easer for a person who is really interested in the development of this project.

If you do not need my help, feel free to remove me from collaborators. I can always make my fork, In the spirit of Open Source and GitHub. I don't want it.

**Comment by erikd** [comment]
> You don't want to merge small, useful, self-descriptive commit just because it is small.

That is a mis-characterization of what I want. Let me be specific.

I want you to work on completing the CMake build system outside the master branch. If this work requires changes to files that are not part of the CMake build systems, they should be submitted as separate PRs and merged onto master as needed.

My suggestion is that you do the following:

* Do whatever it takes to get the CMake build system *complete* on your branch
* Send me a PR with all the changes needed to the non-CMake files and wait for that to be merged.
* Send me PR with the changes to the CMake files.

Doing it this way will be less work for me, keeps me happy and only makes me the bottle neck on two PRs.

**Pull request closed without merging**
