### PR TITLE
Remove unneeded branch of code

### PR DESCRIPTION
**Pull request by evpobr**
With CMake we can configure sndfile.h properly.

### CODE REVIEW

**Comment by erikd** [comment]
This could break the autotool configuration. I'm not ready to replace autotools with CMake. For the time being at least libsndfile will have two configuration methods.

**Comment by evpobr** [comment]
Can you explain please? This build passes Travis CI check with Autotools.

**Comment by erikd** [comment]
I sure it does build with that in Travis because it is a Windows specific hack.

When configured for Windows, but built with MinGW:
```
#if (defined (_MSCVER) || defined (_MSC_VER))
typedef __int64         sf_count_t ;
#define SF_COUNT_MAX            0x7fffffffffffffffi64
#else
typedef __int64 sf_count_t ;
#define SF_COUNT_MAX            0x7FFFFFFFFFFFFFFFLL
#endif
```
The first branch is needed because MSVC does not understand the `LL` type modifier.

**Comment by evpobr** [comment]
Hmm, VS2015 understands `LL`.

**Comment by erikd** [comment]
Earlier versions may not.

**Comment by evpobr** [comment]
You're right, i close this PR.

**Pull request closed without merging**
