### PR TITLE
Supress meaningless MSVC warning in AppVeyor CI builds

### PR DESCRIPTION
**Pull request by evpobr**

### CODE REVIEW

**Comment by evpobr** [comment]
@erikd , restart AppVeyor test please.

**Comment by evpobr** [comment]
Ok, force push will restart it.

**Comment by evpobr** [comment]
Yes, it sucks. I think we need to integrate #452 and drop AppVeyor CI. Can you test it? This [article](https://andrewlock.net/building-an-open-source-github-project-using-azure-devops/) could help.

**Comment by erikd** [comment]
Both windows builds stopped at the same place, namely:
```
38: Test command: C:\projects\libsndfile\CMakeBuild\Debug\write_read_test.exe "caf"
38: Test timeout computed to be: 1500
38:     pcm_test_char                  : char.caf ................ ok
38:     pcm_test_short                 : short.caf ............... ok
38:     pcm_test_24bit                 : 24bit.caf ............... ok
38:     pcm_test_int                   : int.caf ................. ok
38:     pcm_test_float                 : float.caf ............... ok
38:     pcm_test_double                : double.caf .............. ok
38:     pcm_test_short                 : short_le.caf ............ ok
38:     pcm_test_24bit                 : 24bit_le.caf ............ ok
38:     pcm_test_int                   : int_le.caf .............. ok
38:     pcm_test_float                 : float_le.caf ............ ok
38:     pcm_test_double                : double_le.caf ........... ok
```
I also notice that it got to that place after 25 minutes and the build timed out after an hour.

@evpobr Any clue what is going on?

**Comment by evpobr** [comment]
@erikd , nope

**Comment by evpobr** [comment]
@erikd , i seems like AppVeyor tries to check deleted commit. I will create new PR to fix this.

**Comment by evpobr** [comment]
Nope, [Appveyor build](https://ci.appveyor.com/project/evpobr/libsndfile/builds/22230283) is terrible slow. It fails reaching 1 hour limit.

[Azure Pipelines](https://evpobr.visualstudio.com/LibSndFile/_build/results?buildId=62&view=results) takes 14 minutes to build Windows/Linux configurations (the same as both Travis/Appveyor).

**Comment by erikd** [comment]
> Nope, Appveyor build is terrible slow. It fails reaching 1 hour limit.

I really do not think that is the case. The build got to that double test after 25 minutes, and then seems to hang, only to time out at the 1 hour mark.

**Comment by evpobr** [comment]
I want to implement CI testing with GitHub Actions, so this pull request is obsolete.

**Pull request closed without merging**
